[2023-10-27T14:05:08.169+0000] {processor.py:157} INFO - Started process (PID=34) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:08.171+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:05:08.176+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:08.176+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:08.222+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:08.218+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:05:08.231+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:08.323+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:08.322+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:05:08.372+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:08.371+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:00:08.370635+00:00, run_after=2023-10-27T14:05:08.370635+00:00
[2023-10-27T14:05:08.443+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.281 seconds
[2023-10-27T14:05:39.159+0000] {processor.py:157} INFO - Started process (PID=94) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:39.164+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:05:39.175+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:39.173+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:39.245+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:39.234+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:05:39.247+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:05:39.280+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:39.280+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:05:39.328+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:05:39.328+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:05:39.360+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.213 seconds
[2023-10-27T14:06:09.543+0000] {processor.py:157} INFO - Started process (PID=149) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:09.544+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:06:09.550+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:09.550+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:09.568+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:09.567+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:06:09.569+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:09.596+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:09.590+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:06:09.620+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:09.619+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:06:09.641+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.102 seconds
[2023-10-27T14:06:39.860+0000] {processor.py:157} INFO - Started process (PID=204) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:39.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:06:39.879+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:39.877+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:39.918+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:39.914+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:06:39.918+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:06:39.940+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:39.940+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:06:39.975+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:06:39.975+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:06:39.997+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.153 seconds
[2023-10-27T14:07:10.980+0000] {processor.py:157} INFO - Started process (PID=259) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:10.983+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:07:10.989+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:10.988+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:11.024+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:11.022+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:07:11.024+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:11.044+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:11.044+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:07:11.070+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:11.070+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:07:11.087+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.121 seconds
[2023-10-27T14:07:41.705+0000] {processor.py:157} INFO - Started process (PID=314) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:41.708+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:07:41.712+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:41.712+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:41.772+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:41.766+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:07:41.772+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:07:41.803+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:41.803+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:07:41.829+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:07:41.829+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:07:41.856+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.157 seconds
[2023-10-27T14:08:12.145+0000] {processor.py:157} INFO - Started process (PID=370) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:12.147+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:08:12.154+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:12.154+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:12.198+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:12.197+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:08:12.199+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:12.220+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:12.220+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:08:12.254+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:12.254+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:08:12.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.144 seconds
[2023-10-27T14:08:42.509+0000] {processor.py:157} INFO - Started process (PID=424) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:42.515+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:08:42.531+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:42.528+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:42.617+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:42.613+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:08:42.618+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:08:42.688+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:42.688+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:08:42.752+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:08:42.752+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:08:42.785+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.302 seconds
[2023-10-27T14:09:13.331+0000] {processor.py:157} INFO - Started process (PID=479) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:13.356+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:09:13.393+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:13.388+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:13.557+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:13.549+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:09:13.560+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:13.669+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:13.669+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:09:13.799+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:13.798+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:09:13.865+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.582 seconds
[2023-10-27T14:09:44.720+0000] {processor.py:157} INFO - Started process (PID=533) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:44.723+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:09:44.733+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:44.732+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:44.779+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:44.776+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:09:44.779+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:09:44.809+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:44.808+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:09:44.841+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:09:44.841+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:05:08.370635+00:00, run_after=2023-10-27T14:10:08.370635+00:00
[2023-10-27T14:09:44.860+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.146 seconds
[2023-10-27T14:10:15.093+0000] {processor.py:157} INFO - Started process (PID=588) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:15.100+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:10:15.118+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:15.117+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:15.171+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:15.167+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:10:15.171+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:15.217+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:15.217+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:10:15.282+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:15.282+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:10:08.370635+00:00, run_after=2023-10-27T14:15:08.370635+00:00
[2023-10-27T14:10:15.310+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.231 seconds
[2023-10-27T14:10:45.647+0000] {processor.py:157} INFO - Started process (PID=643) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:45.659+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:10:45.665+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:45.665+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:45.696+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:45.694+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:10:45.697+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:10:45.743+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:45.742+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:10:45.776+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:10:45.776+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:10:08.370635+00:00, run_after=2023-10-27T14:15:08.370635+00:00
[2023-10-27T14:10:45.796+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.160 seconds
[2023-10-27T14:11:16.223+0000] {processor.py:157} INFO - Started process (PID=698) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:16.226+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:11:16.232+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:16.231+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:16.257+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:16.255+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:11:16.258+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:16.337+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:16.337+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:11:16.388+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:16.388+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:10:08.370635+00:00, run_after=2023-10-27T14:15:08.370635+00:00
[2023-10-27T14:11:16.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.196 seconds
[2023-10-27T14:11:46.663+0000] {processor.py:157} INFO - Started process (PID=753) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:46.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:11:46.695+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:46.694+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:46.752+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:46.749+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:11:46.753+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:11:46.819+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:46.819+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:11:46.891+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:11:46.891+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:10:08.370635+00:00, run_after=2023-10-27T14:15:08.370635+00:00
[2023-10-27T14:11:46.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.279 seconds
[2023-10-27T14:12:17.087+0000] {processor.py:157} INFO - Started process (PID=808) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:17.090+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:12:17.099+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:17.098+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:17.141+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:17.138+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:12:17.141+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:17.229+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:17.229+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:12:17.291+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:17.290+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:12:09.926873+00:00, run_after=2023-10-27T14:17:09.926873+00:00
[2023-10-27T14:12:17.323+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.249 seconds
[2023-10-27T14:12:47.509+0000] {processor.py:157} INFO - Started process (PID=863) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:47.512+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:12:47.521+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:47.521+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:47.556+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:47.555+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:12:47.557+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:12:47.610+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:47.609+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:12:47.656+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:12:47.656+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:12:09.926873+00:00, run_after=2023-10-27T14:17:09.926873+00:00
[2023-10-27T14:12:47.678+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.179 seconds
[2023-10-27T14:13:17.815+0000] {processor.py:157} INFO - Started process (PID=918) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:17.822+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:13:17.838+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:17.837+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:17.888+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:17.882+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:13:17.892+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:17.943+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:17.943+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:13:17.979+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:17.978+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:12:09.926873+00:00, run_after=2023-10-27T14:17:09.926873+00:00
[2023-10-27T14:13:18.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.210 seconds
[2023-10-27T14:13:48.173+0000] {processor.py:157} INFO - Started process (PID=973) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:48.177+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:13:48.198+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:48.198+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:48.262+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:48.259+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:13:48.263+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:13:48.326+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:48.326+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:13:48.391+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:13:48.391+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:12:09.926873+00:00, run_after=2023-10-27T14:17:09.926873+00:00
[2023-10-27T14:13:48.431+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.285 seconds
[2023-10-27T14:14:19.112+0000] {processor.py:157} INFO - Started process (PID=1032) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:19.114+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:14:19.120+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:19.120+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:19.151+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:19.149+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:14:19.153+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:19.189+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:19.188+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:14:19.218+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:19.218+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:14:15.076434+00:00, run_after=2023-10-27T14:19:15.076434+00:00
[2023-10-27T14:14:19.234+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.129 seconds
[2023-10-27T14:14:49.915+0000] {processor.py:157} INFO - Started process (PID=1087) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:49.918+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:14:49.942+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:49.940+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:50.004+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:50.002+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:14:50.006+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:14:50.042+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:50.042+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:14:50.093+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:14:50.093+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:14:15.076434+00:00, run_after=2023-10-27T14:19:15.076434+00:00
[2023-10-27T14:14:50.126+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.225 seconds
[2023-10-27T14:15:20.304+0000] {processor.py:157} INFO - Started process (PID=1142) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:20.313+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:15:20.320+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:20.319+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:20.362+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:20.358+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:15:20.362+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:20.403+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:20.402+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:15:20.454+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:20.453+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:15:12.921512+00:00, run_after=2023-10-27T14:20:12.921512+00:00
[2023-10-27T14:15:20.482+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.201 seconds
[2023-10-27T14:15:50.533+0000] {processor.py:157} INFO - Started process (PID=1197) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:50.535+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:15:50.539+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:50.539+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:50.553+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:50.550+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:15:50.553+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:15:50.581+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:50.581+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:15:50.606+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:15:50.606+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:15:12.921512+00:00, run_after=2023-10-27T14:20:12.921512+00:00
[2023-10-27T14:15:50.623+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.093 seconds
[2023-10-27T14:16:21.108+0000] {processor.py:157} INFO - Started process (PID=1252) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:21.112+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:16:21.121+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:21.120+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:21.168+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:21.165+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:16:21.169+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:21.233+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:21.233+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:16:21.286+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:21.286+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:15:12.921512+00:00, run_after=2023-10-27T14:20:12.921512+00:00
[2023-10-27T14:16:21.309+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.231 seconds
[2023-10-27T14:16:52.046+0000] {processor.py:157} INFO - Started process (PID=1307) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:52.050+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:16:52.064+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:52.063+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:52.110+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:52.101+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:16:52.111+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:16:52.154+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:52.153+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:16:52.186+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:16:52.186+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:15:12.921512+00:00, run_after=2023-10-27T14:20:12.921512+00:00
[2023-10-27T14:16:52.205+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.182 seconds
[2023-10-27T14:17:23.065+0000] {processor.py:157} INFO - Started process (PID=1362) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:23.068+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:17:23.077+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:23.076+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:23.129+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:23.126+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:17:23.130+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:23.190+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:23.189+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:17:23.248+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:23.247+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:17:14.723330+00:00, run_after=2023-10-27T14:22:14.723330+00:00
[2023-10-27T14:17:23.282+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.244 seconds
[2023-10-27T14:17:53.766+0000] {processor.py:157} INFO - Started process (PID=1421) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:53.773+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:17:53.797+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:53.795+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:53.884+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:53.877+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:17:53.886+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:17:53.989+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:53.988+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:17:54.189+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:17:54.188+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:17:14.723330+00:00, run_after=2023-10-27T14:22:14.723330+00:00
[2023-10-27T14:17:54.244+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.522 seconds
[2023-10-27T14:18:24.519+0000] {processor.py:157} INFO - Started process (PID=1475) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:24.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:18:24.536+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:24.534+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:24.648+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:24.643+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:18:24.649+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:24.796+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:24.795+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:18:24.911+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:24.911+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:17:14.723330+00:00, run_after=2023-10-27T14:22:14.723330+00:00
[2023-10-27T14:18:24.969+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.473 seconds
[2023-10-27T14:18:55.694+0000] {processor.py:157} INFO - Started process (PID=1530) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:55.698+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:18:55.705+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:55.704+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:55.755+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:55.753+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:18:55.756+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:18:55.779+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:55.779+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:18:55.819+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:18:55.819+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:17:14.723330+00:00, run_after=2023-10-27T14:22:14.723330+00:00
[2023-10-27T14:18:55.847+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.162 seconds
[2023-10-27T14:19:26.887+0000] {processor.py:157} INFO - Started process (PID=1585) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:26.890+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:19:26.898+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:26.898+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:26.947+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:26.944+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:19:26.947+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:26.992+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:26.992+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:19:27.050+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:27.050+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:19:21.015664+00:00, run_after=2023-10-27T14:24:21.015664+00:00
[2023-10-27T14:19:27.079+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.207 seconds
[2023-10-27T14:19:57.802+0000] {processor.py:157} INFO - Started process (PID=1640) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:57.809+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:19:57.815+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:57.815+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:57.867+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:57.864+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:19:57.867+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:19:57.900+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:57.900+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:19:57.927+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:19:57.927+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:19:21.015664+00:00, run_after=2023-10-27T14:24:21.015664+00:00
[2023-10-27T14:19:57.943+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.148 seconds
[2023-10-27T14:20:28.785+0000] {processor.py:157} INFO - Started process (PID=1695) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:28.789+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:20:28.797+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:28.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:28.816+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:28.815+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:20:28.816+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:28.842+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:28.842+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:20:28.867+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:28.867+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:20:17.600938+00:00, run_after=2023-10-27T14:25:17.600938+00:00
[2023-10-27T14:20:28.885+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.104 seconds
[2023-10-27T14:20:59.905+0000] {processor.py:157} INFO - Started process (PID=1750) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:59.907+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:20:59.914+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:59.913+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:59.960+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:59.957+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:20:59.960+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:20:59.993+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:20:59.993+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:21:00.033+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:21:00.032+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:20:17.600938+00:00, run_after=2023-10-27T14:25:17.600938+00:00
[2023-10-27T14:21:00.081+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.188 seconds
[2023-10-27T14:21:30.862+0000] {processor.py:157} INFO - Started process (PID=1805) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:21:30.866+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:21:30.888+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:21:30.886+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:21:30.932+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:21:30.924+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:21:30.933+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:21:30.980+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:21:30.980+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:21:31.022+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:21:31.022+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:20:17.600938+00:00, run_after=2023-10-27T14:25:17.600938+00:00
[2023-10-27T14:21:31.043+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.191 seconds
[2023-10-27T14:22:01.592+0000] {processor.py:157} INFO - Started process (PID=1860) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:01.595+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:22:01.599+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:01.599+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:01.628+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:01.626+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:22:01.628+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:01.650+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:01.650+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:22:01.672+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:01.671+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:20:17.600938+00:00, run_after=2023-10-27T14:25:17.600938+00:00
[2023-10-27T14:22:01.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.099 seconds
[2023-10-27T14:22:32.204+0000] {processor.py:157} INFO - Started process (PID=1915) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:32.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:22:32.227+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:32.224+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:32.276+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:32.270+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:22:32.277+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:22:32.334+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:32.333+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:22:32.382+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:22:32.382+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:22:21.306667+00:00, run_after=2023-10-27T14:27:21.306667+00:00
[2023-10-27T14:22:32.424+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.233 seconds
[2023-10-27T14:23:03.089+0000] {processor.py:157} INFO - Started process (PID=1969) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:03.091+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:23:03.098+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:03.097+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:03.123+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:03.121+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:23:03.123+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:03.153+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:03.153+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:23:03.186+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:03.185+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:22:21.306667+00:00, run_after=2023-10-27T14:27:21.306667+00:00
[2023-10-27T14:23:03.211+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.129 seconds
[2023-10-27T14:23:33.925+0000] {processor.py:157} INFO - Started process (PID=2023) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:33.927+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:23:33.932+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:33.931+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:33.966+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:33.965+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:23:33.966+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:23:33.983+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:33.983+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:23:34.265+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:23:34.265+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:22:21.306667+00:00, run_after=2023-10-27T14:27:21.306667+00:00
[2023-10-27T14:23:34.278+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.358 seconds
[2023-10-27T14:24:04.686+0000] {processor.py:157} INFO - Started process (PID=2078) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:04.688+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:24:04.692+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:04.692+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:04.707+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:04.706+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:24:04.709+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:04.730+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:04.730+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:24:04.752+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:04.752+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:22:21.306667+00:00, run_after=2023-10-27T14:27:21.306667+00:00
[2023-10-27T14:24:04.766+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.087 seconds
[2023-10-27T14:24:35.062+0000] {processor.py:157} INFO - Started process (PID=2133) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:35.066+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:24:35.076+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:35.075+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:35.137+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:35.133+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:24:35.138+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:24:35.187+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:35.187+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:24:35.236+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:24:35.236+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:24:26.543952+00:00, run_after=2023-10-27T14:29:26.543952+00:00
[2023-10-27T14:24:35.274+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.260 seconds
[2023-10-27T14:25:06.283+0000] {processor.py:157} INFO - Started process (PID=2188) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:06.285+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:25:06.292+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:06.291+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:06.324+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:06.320+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:25:06.324+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:06.358+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:06.358+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:25:06.391+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:06.390+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:24:26.543952+00:00, run_after=2023-10-27T14:29:26.543952+00:00
[2023-10-27T14:25:06.410+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.137 seconds
[2023-10-27T14:25:37.486+0000] {processor.py:157} INFO - Started process (PID=2243) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:37.494+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:25:37.519+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:37.519+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:37.596+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:37.590+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:25:37.597+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:25:37.669+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:37.669+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:25:38.444+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:25:38.441+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:25:25.074943+00:00, run_after=2023-10-27T14:30:25.074943+00:00
[2023-10-27T14:25:38.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 1.022 seconds
[2023-10-27T14:26:08.784+0000] {processor.py:157} INFO - Started process (PID=2298) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:08.787+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:26:08.798+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:08.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:08.916+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:08.913+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:26:08.918+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:08.979+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:08.979+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:26:09.066+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:09.065+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:25:25.074943+00:00, run_after=2023-10-27T14:30:25.074943+00:00
[2023-10-27T14:26:09.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 1.194 seconds
[2023-10-27T14:26:40.120+0000] {processor.py:157} INFO - Started process (PID=2353) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:40.128+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:26:40.152+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:40.151+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:40.202+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:40.200+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:26:40.203+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:26:40.256+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:40.256+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:26:40.321+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:26:40.321+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:25:25.074943+00:00, run_after=2023-10-27T14:30:25.074943+00:00
[2023-10-27T14:26:40.344+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.246 seconds
[2023-10-27T14:27:10.457+0000] {processor.py:157} INFO - Started process (PID=2408) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:10.462+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:27:10.470+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:10.469+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:10.506+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:10.503+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:27:10.510+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:10.553+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:10.553+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:27:10.947+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:10.947+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:25:25.074943+00:00, run_after=2023-10-27T14:30:25.074943+00:00
[2023-10-27T14:27:10.960+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.524 seconds
[2023-10-27T14:27:41.550+0000] {processor.py:157} INFO - Started process (PID=2463) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:41.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:27:41.569+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:41.568+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:41.608+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:41.602+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:27:41.611+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:27:41.675+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:41.674+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:27:42.344+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:27:42.342+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:27:32.795582+00:00, run_after=2023-10-27T14:32:32.795582+00:00
[2023-10-27T14:27:42.368+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.841 seconds
[2023-10-27T14:28:13.396+0000] {processor.py:157} INFO - Started process (PID=2517) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:13.398+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:28:13.403+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:13.403+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:13.460+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:13.458+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:28:13.460+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:13.486+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:13.485+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:28:13.514+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:13.514+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:27:32.795582+00:00, run_after=2023-10-27T14:32:32.795582+00:00
[2023-10-27T14:28:13.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.145 seconds
[2023-10-27T14:28:43.663+0000] {processor.py:157} INFO - Started process (PID=2572) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:43.668+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:28:43.693+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:43.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:43.767+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:43.764+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:28:43.769+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:28:44.637+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:44.636+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:28:44.701+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:28:44.701+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:27:32.795582+00:00, run_after=2023-10-27T14:32:32.795582+00:00
[2023-10-27T14:28:44.733+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 1.088 seconds
[2023-10-27T14:29:14.866+0000] {processor.py:157} INFO - Started process (PID=2626) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:14.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:29:14.875+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:14.874+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:14.920+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:14.918+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:29:14.923+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:14.956+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:14.955+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:29:14.991+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:14.990+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:27:32.795582+00:00, run_after=2023-10-27T14:32:32.795582+00:00
[2023-10-27T14:29:15.012+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.157 seconds
[2023-10-27T14:29:45.427+0000] {processor.py:157} INFO - Started process (PID=2681) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:45.431+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:29:45.437+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:45.436+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:45.480+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:45.478+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:29:45.481+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:29:45.522+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:45.522+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:29:45.569+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:29:45.568+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:29:36.467140+00:00, run_after=2023-10-27T14:34:36.467140+00:00
[2023-10-27T14:29:45.588+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.174 seconds
[2023-10-27T14:30:15.681+0000] {processor.py:157} INFO - Started process (PID=2736) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:15.683+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:30:15.690+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:15.690+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:15.721+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:15.718+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:30:15.722+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:15.757+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:15.756+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:30:15.805+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:15.805+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:29:36.467140+00:00, run_after=2023-10-27T14:34:36.467140+00:00
[2023-10-27T14:30:15.826+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.160 seconds
[2023-10-27T14:30:45.920+0000] {processor.py:157} INFO - Started process (PID=2791) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:45.924+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:30:45.933+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:45.933+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:45.960+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:45.959+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:30:45.961+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:30:45.989+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:45.989+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:30:46.016+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:30:46.015+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:30:31.164359+00:00, run_after=2023-10-27T14:35:31.164359+00:00
[2023-10-27T14:30:46.034+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.135 seconds
[2023-10-27T14:31:16.647+0000] {processor.py:157} INFO - Started process (PID=2846) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:16.656+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:31:16.658+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:16.658+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:16.683+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:16.682+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:31:16.684+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:16.703+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:16.703+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:31:16.725+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:16.725+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:30:31.164359+00:00, run_after=2023-10-27T14:35:31.164359+00:00
[2023-10-27T14:31:16.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.098 seconds
[2023-10-27T14:31:47.132+0000] {processor.py:157} INFO - Started process (PID=2901) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:47.136+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:31:47.156+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:47.155+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:47.202+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:47.200+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:31:47.203+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:31:47.238+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:47.238+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:31:47.270+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:31:47.270+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:30:31.164359+00:00, run_after=2023-10-27T14:35:31.164359+00:00
[2023-10-27T14:31:47.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.162 seconds
[2023-10-27T14:32:17.553+0000] {processor.py:157} INFO - Started process (PID=2956) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:17.557+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:32:17.564+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:17.562+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:17.588+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:17.586+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:32:17.589+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:17.617+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:17.617+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:32:17.644+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:17.644+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:30:31.164359+00:00, run_after=2023-10-27T14:35:31.164359+00:00
[2023-10-27T14:32:17.662+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.115 seconds
[2023-10-27T14:32:47.802+0000] {processor.py:157} INFO - Started process (PID=3011) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:47.804+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:32:47.811+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:47.811+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:47.839+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:47.834+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:32:47.839+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:32:47.899+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:47.898+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:32:47.934+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:32:47.934+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:32:37.823310+00:00, run_after=2023-10-27T14:37:37.823310+00:00
[2023-10-27T14:32:47.956+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.161 seconds
[2023-10-27T14:33:18.705+0000] {processor.py:157} INFO - Started process (PID=3066) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:18.713+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:33:18.724+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:18.722+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:18.757+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:18.755+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:33:18.759+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:18.814+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:18.814+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:33:18.865+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:18.865+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:32:37.823310+00:00, run_after=2023-10-27T14:37:37.823310+00:00
[2023-10-27T14:33:18.889+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.220 seconds
[2023-10-27T14:33:49.100+0000] {processor.py:157} INFO - Started process (PID=3121) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:49.105+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:33:49.111+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:49.111+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:49.140+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:49.138+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:33:49.140+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:33:49.198+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:49.198+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:33:49.244+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:33:49.244+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:32:37.823310+00:00, run_after=2023-10-27T14:37:37.823310+00:00
[2023-10-27T14:33:49.264+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.176 seconds
[2023-10-27T14:34:19.497+0000] {processor.py:157} INFO - Started process (PID=3176) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:19.502+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:34:19.512+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:19.510+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:19.615+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:19.611+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:34:19.616+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:19.695+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:19.695+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:34:19.757+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:19.756+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:32:37.823310+00:00, run_after=2023-10-27T14:37:37.823310+00:00
[2023-10-27T14:34:19.798+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.326 seconds
[2023-10-27T14:34:50.261+0000] {processor.py:157} INFO - Started process (PID=3230) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:50.266+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:34:50.279+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:50.278+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:50.352+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:50.341+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:34:50.353+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:34:50.422+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:50.422+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:34:50.468+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:34:50.468+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:34:43.489556+00:00, run_after=2023-10-27T14:39:43.489556+00:00
[2023-10-27T14:34:50.510+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.295 seconds
[2023-10-27T14:35:20.812+0000] {processor.py:157} INFO - Started process (PID=3284) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:20.816+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:35:20.823+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:20.822+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:20.853+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:20.852+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:35:20.854+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:20.889+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:20.889+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:35:20.918+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:20.918+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:34:43.489556+00:00, run_after=2023-10-27T14:39:43.489556+00:00
[2023-10-27T14:35:20.936+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.129 seconds
[2023-10-27T14:35:51.280+0000] {processor.py:157} INFO - Started process (PID=3339) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:51.282+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:35:51.289+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:51.288+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:51.316+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:51.315+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:35:51.317+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:35:51.343+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:51.343+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:35:51.375+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:35:51.375+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:35:34.739104+00:00, run_after=2023-10-27T14:40:34.739104+00:00
[2023-10-27T14:35:51.397+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.123 seconds
[2023-10-27T14:36:21.499+0000] {processor.py:157} INFO - Started process (PID=3394) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:21.503+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:36:21.523+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:21.521+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:21.576+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:21.574+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:36:21.578+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:21.633+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:21.632+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:36:21.695+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:21.695+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:35:34.739104+00:00, run_after=2023-10-27T14:40:34.739104+00:00
[2023-10-27T14:36:21.725+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.235 seconds
[2023-10-27T14:36:52.028+0000] {processor.py:157} INFO - Started process (PID=3448) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:52.031+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:36:52.035+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:52.035+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:52.060+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:52.059+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:36:52.062+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:36:52.093+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:52.093+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:36:52.121+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:36:52.121+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:35:34.739104+00:00, run_after=2023-10-27T14:40:34.739104+00:00
[2023-10-27T14:36:52.142+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.126 seconds
[2023-10-27T14:37:22.527+0000] {processor.py:157} INFO - Started process (PID=3502) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:22.532+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:37:22.544+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:22.544+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:22.600+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:22.599+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:37:22.601+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:22.649+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:22.649+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:37:22.696+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:22.695+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:35:34.739104+00:00, run_after=2023-10-27T14:40:34.739104+00:00
[2023-10-27T14:37:22.732+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.215 seconds
[2023-10-27T14:37:53.203+0000] {processor.py:157} INFO - Started process (PID=3557) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:53.208+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:37:53.213+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:53.213+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:53.245+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:53.243+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:37:53.245+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:37:53.266+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:53.266+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:37:53.303+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:37:53.303+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:37:45.233285+00:00, run_after=2023-10-27T14:42:45.233285+00:00
[2023-10-27T14:37:53.324+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.132 seconds
[2023-10-27T14:38:23.531+0000] {processor.py:157} INFO - Started process (PID=3612) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:23.534+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:38:23.537+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:23.537+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:23.554+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:23.553+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:38:23.555+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:23.587+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:23.587+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:38:23.618+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:23.617+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:37:45.233285+00:00, run_after=2023-10-27T14:42:45.233285+00:00
[2023-10-27T14:38:23.635+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.107 seconds
[2023-10-27T14:38:54.197+0000] {processor.py:157} INFO - Started process (PID=3666) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:54.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:38:54.209+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:54.209+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:54.261+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:54.258+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:38:54.261+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:38:54.290+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:54.290+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:38:54.343+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:38:54.343+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:37:45.233285+00:00, run_after=2023-10-27T14:42:45.233285+00:00
[2023-10-27T14:38:54.375+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.184 seconds
[2023-10-27T14:39:24.587+0000] {processor.py:157} INFO - Started process (PID=3721) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:24.594+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:39:24.602+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:24.602+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:24.660+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:24.659+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:39:24.661+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:24.694+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:24.694+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:39:24.735+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:24.735+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:37:45.233285+00:00, run_after=2023-10-27T14:42:45.233285+00:00
[2023-10-27T14:39:24.769+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.211 seconds
[2023-10-27T14:39:55.207+0000] {processor.py:157} INFO - Started process (PID=3776) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:55.214+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:39:55.225+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:55.224+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:55.286+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:55.283+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:39:55.286+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:39:55.364+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:55.364+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:39:55.414+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:39:55.414+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:39:50.764342+00:00, run_after=2023-10-27T14:44:50.764342+00:00
[2023-10-27T14:39:55.454+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.278 seconds
[2023-10-27T14:40:25.560+0000] {processor.py:157} INFO - Started process (PID=3831) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:25.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:40:25.577+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:25.577+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:25.646+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:25.643+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:40:25.646+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:25.672+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:25.672+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:40:25.705+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:25.705+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:39:50.764342+00:00, run_after=2023-10-27T14:44:50.764342+00:00
[2023-10-27T14:40:25.729+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.180 seconds
[2023-10-27T14:40:56.404+0000] {processor.py:157} INFO - Started process (PID=3886) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:56.409+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:40:56.420+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:56.419+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:56.473+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:56.470+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:40:56.474+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:40:56.504+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:56.504+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:40:56.536+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:40:56.536+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:40:39.821332+00:00, run_after=2023-10-27T14:45:39.821332+00:00
[2023-10-27T14:40:56.554+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.165 seconds
[2023-10-27T14:41:27.241+0000] {processor.py:157} INFO - Started process (PID=3941) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:27.245+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:41:27.254+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:27.253+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:27.303+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:27.301+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:41:27.304+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:27.335+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:27.334+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:41:27.367+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:27.367+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:40:39.821332+00:00, run_after=2023-10-27T14:45:39.821332+00:00
[2023-10-27T14:41:27.388+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.172 seconds
[2023-10-27T14:41:58.097+0000] {processor.py:157} INFO - Started process (PID=3996) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:58.099+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:41:58.106+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:58.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:58.143+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:58.141+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:41:58.143+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:41:58.176+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:58.176+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:41:58.213+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:41:58.213+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:40:39.821332+00:00, run_after=2023-10-27T14:45:39.821332+00:00
[2023-10-27T14:41:58.240+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.151 seconds
[2023-10-27T14:42:29.307+0000] {processor.py:157} INFO - Started process (PID=4051) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:29.312+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:42:29.318+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:29.317+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:29.367+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:29.364+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:42:29.367+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:29.406+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:29.406+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:42:29.441+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:29.441+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:40:39.821332+00:00, run_after=2023-10-27T14:45:39.821332+00:00
[2023-10-27T14:42:29.466+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.167 seconds
[2023-10-27T14:42:59.729+0000] {processor.py:157} INFO - Started process (PID=4106) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:59.733+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:42:59.753+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:59.751+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:59.802+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:59.800+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:42:59.802+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:42:59.860+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:59.860+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:42:59.906+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:42:59.906+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:42:53.072865+00:00, run_after=2023-10-27T14:47:53.072865+00:00
[2023-10-27T14:42:59.930+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.217 seconds
[2023-10-27T14:43:30.547+0000] {processor.py:157} INFO - Started process (PID=4161) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:43:30.551+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:43:30.561+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:43:30.560+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:43:30.621+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:43:30.619+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:43:30.623+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:43:30.688+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:43:30.687+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:43:30.743+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:43:30.743+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:42:53.072865+00:00, run_after=2023-10-27T14:47:53.072865+00:00
[2023-10-27T14:43:30.773+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.242 seconds
[2023-10-27T14:44:00.980+0000] {processor.py:157} INFO - Started process (PID=4216) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:00.984+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:44:00.993+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:00.992+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:01.048+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:01.035+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:44:01.049+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:01.083+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:01.083+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:44:01.120+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:01.120+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:42:53.072865+00:00, run_after=2023-10-27T14:47:53.072865+00:00
[2023-10-27T14:44:01.144+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.176 seconds
[2023-10-27T14:44:31.194+0000] {processor.py:157} INFO - Started process (PID=4272) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:31.195+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:44:31.197+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:31.197+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:31.212+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:31.211+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:44:31.213+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:44:31.240+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:31.239+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:44:31.266+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:44:31.266+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:42:53.072865+00:00, run_after=2023-10-27T14:47:53.072865+00:00
[2023-10-27T14:44:31.283+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.092 seconds
[2023-10-27T14:45:02.791+0000] {processor.py:157} INFO - Started process (PID=4332) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:02.898+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:45:02.930+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:02.929+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:03.022+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:03.016+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:45:03.023+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:03.102+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:03.101+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:45:03.196+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:03.196+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:44:57.500117+00:00, run_after=2023-10-27T14:49:57.500117+00:00
[2023-10-27T14:45:03.235+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.660 seconds
[2023-10-27T14:45:34.219+0000] {processor.py:157} INFO - Started process (PID=4388) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:34.227+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:45:34.238+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:34.238+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:34.286+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:34.284+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:45:34.287+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:45:34.322+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:34.322+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:45:34.357+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:45:34.356+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:44:57.500117+00:00, run_after=2023-10-27T14:49:57.500117+00:00
[2023-10-27T14:45:34.389+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.179 seconds
[2023-10-27T14:46:04.921+0000] {processor.py:157} INFO - Started process (PID=4443) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:04.922+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:46:04.928+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:04.927+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:04.972+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:04.970+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:46:04.973+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:05.001+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:05.001+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:46:05.025+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:05.025+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:45:45.020326+00:00, run_after=2023-10-27T14:50:45.020326+00:00
[2023-10-27T14:46:05.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.127 seconds
[2023-10-27T14:46:35.359+0000] {processor.py:157} INFO - Started process (PID=4498) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:35.362+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:46:35.368+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:35.367+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:35.434+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:35.423+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:46:35.435+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:46:35.472+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:35.472+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:46:35.504+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:46:35.504+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:45:45.020326+00:00, run_after=2023-10-27T14:50:45.020326+00:00
[2023-10-27T14:46:35.525+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.178 seconds
[2023-10-27T14:47:06.198+0000] {processor.py:157} INFO - Started process (PID=4552) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:06.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:47:06.211+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:06.210+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:06.241+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:06.238+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:47:06.241+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:06.290+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:06.290+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:47:06.323+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:06.323+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:45:45.020326+00:00, run_after=2023-10-27T14:50:45.020326+00:00
[2023-10-27T14:47:06.342+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.156 seconds
[2023-10-27T14:47:36.601+0000] {processor.py:157} INFO - Started process (PID=4606) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:36.604+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:47:36.612+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:36.611+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:36.663+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:36.661+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:47:36.663+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:47:36.700+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:36.700+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:47:36.732+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:47:36.732+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:45:45.020326+00:00, run_after=2023-10-27T14:50:45.020326+00:00
[2023-10-27T14:47:36.752+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.163 seconds
[2023-10-27T14:48:06.949+0000] {processor.py:157} INFO - Started process (PID=4661) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:06.955+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:48:06.965+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:06.964+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:07.003+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:06.997+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:48:07.004+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:07.050+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:07.050+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:48:07.081+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:07.081+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:47:59.473429+00:00, run_after=2023-10-27T14:52:59.473429+00:00
[2023-10-27T14:48:07.113+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.179 seconds
[2023-10-27T14:48:37.520+0000] {processor.py:157} INFO - Started process (PID=4716) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:37.525+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:48:37.539+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:37.538+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:37.585+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:37.583+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:48:37.586+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:48:37.659+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:37.658+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:48:37.712+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:48:37.712+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:47:59.473429+00:00, run_after=2023-10-27T14:52:59.473429+00:00
[2023-10-27T14:48:37.748+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.242 seconds
[2023-10-27T14:49:08.790+0000] {processor.py:157} INFO - Started process (PID=4771) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:08.817+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:49:08.826+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:08.826+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:08.882+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:08.881+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:49:08.888+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:09.144+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:09.143+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:49:09.246+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:09.246+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:47:59.473429+00:00, run_after=2023-10-27T14:52:59.473429+00:00
[2023-10-27T14:49:09.301+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.539 seconds
[2023-10-27T14:49:39.708+0000] {processor.py:157} INFO - Started process (PID=4826) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:39.712+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:49:39.719+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:39.718+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:39.754+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:39.752+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:49:39.755+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:49:39.812+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:39.812+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:49:39.857+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:49:39.857+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:47:59.473429+00:00, run_after=2023-10-27T14:52:59.473429+00:00
[2023-10-27T14:49:39.876+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.181 seconds
[2023-10-27T14:50:11.176+0000] {processor.py:157} INFO - Started process (PID=4880) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:11.180+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:50:11.218+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:11.215+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:11.288+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:11.283+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:50:11.292+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:11.416+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:11.414+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:50:11.746+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:11.743+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:06.780583+00:00, run_after=2023-10-27T14:55:06.780583+00:00
[2023-10-27T14:50:11.882+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.725 seconds
[2023-10-27T14:50:43.015+0000] {processor.py:157} INFO - Started process (PID=4934) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:43.020+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:50:43.030+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:43.029+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:43.084+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:43.082+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:50:43.084+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:50:43.122+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:43.122+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:50:43.155+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:50:43.155+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:06.780583+00:00, run_after=2023-10-27T14:55:06.780583+00:00
[2023-10-27T14:50:43.176+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.181 seconds
[2023-10-27T14:51:13.600+0000] {processor.py:157} INFO - Started process (PID=4989) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:13.603+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:51:13.605+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:13.605+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:13.634+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:13.633+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:51:13.634+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:13.650+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:13.650+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:51:13.672+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:13.671+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:50.416484+00:00, run_after=2023-10-27T14:55:50.416484+00:00
[2023-10-27T14:51:13.686+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.092 seconds
[2023-10-27T14:51:43.900+0000] {processor.py:157} INFO - Started process (PID=5044) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:43.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:51:43.914+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:43.912+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:43.957+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:43.948+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:51:43.960+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:51:44.016+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:44.016+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:51:44.056+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:51:44.056+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:50.416484+00:00, run_after=2023-10-27T14:55:50.416484+00:00
[2023-10-27T14:51:44.080+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.198 seconds
[2023-10-27T14:52:14.198+0000] {processor.py:157} INFO - Started process (PID=5099) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:14.201+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:52:14.208+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:14.207+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:14.266+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:14.264+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:52:14.267+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:14.315+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:14.314+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:52:14.354+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:14.354+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:50.416484+00:00, run_after=2023-10-27T14:55:50.416484+00:00
[2023-10-27T14:52:14.384+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.200 seconds
[2023-10-27T14:52:44.683+0000] {processor.py:157} INFO - Started process (PID=5154) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:44.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:52:44.690+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:44.689+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:44.711+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:44.710+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:52:44.711+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:52:44.737+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:44.737+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:52:44.758+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:52:44.758+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:50:50.416484+00:00, run_after=2023-10-27T14:55:50.416484+00:00
[2023-10-27T14:52:44.777+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.101 seconds
[2023-10-27T14:53:15.433+0000] {processor.py:157} INFO - Started process (PID=5209) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:15.442+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:53:15.459+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:15.457+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:15.553+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:15.549+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:53:15.555+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:15.644+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:15.644+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:53:15.715+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:15.715+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:53:03.340842+00:00, run_after=2023-10-27T14:58:03.340842+00:00
[2023-10-27T14:53:15.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.366 seconds
[2023-10-27T14:53:46.249+0000] {processor.py:157} INFO - Started process (PID=5264) to work on /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:46.253+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/scraping/cryptopanic.py for tasks to queue
[2023-10-27T14:53:46.260+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:46.260+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:46.300+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:46.298+0000] {templater.py:76} ERROR - Failed to resolve template field 'bash_command'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/template/templater.py", line 74, in resolve_template_files
    setattr(self, field, env.loader.get_source(env, content)[0])  # type: ignore
  File "/home/airflow/.local/lib/python3.8/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ./start.sh
[2023-10-27T14:53:46.301+0000] {processor.py:839} INFO - DAG(s) dict_keys(['scrap_scryptopanic']) retrieved from /opt/airflow/dags/scraping/cryptopanic.py
[2023-10-27T14:53:46.341+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:46.340+0000] {dag.py:2941} INFO - Sync 1 DAGs
[2023-10-27T14:53:46.382+0000] {logging_mixin.py:151} INFO - [2023-10-27T14:53:46.382+0000] {dag.py:3722} INFO - Setting next_dagrun for scrap_scryptopanic to 2023-10-27T14:53:03.340842+00:00, run_after=2023-10-27T14:58:03.340842+00:00
[2023-10-27T14:53:46.401+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/scraping/cryptopanic.py took 0.167 seconds
